name: CD

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install
    - name: Run tests
      run: vendor/bin/phpunit
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Deploy to master
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USER }}
        host: ${{ secrets.SSH_HOST }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /var/www/alchris.web.id && chmod +x server_deploy.sh && ./server_deploy.sh'